version: '3.8'

services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
      - AI_OCR_PROVIDER=local
      - AI_EXTRACT_PROVIDER=local
      - LOCAL_STORAGE_PATH=/app/data
      - FAISS_INDEX_PATH=/app/faiss_index
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=documents
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_ops
    volumes:
      - ./:/app
      - ai_data:/app/data
      - ai_faiss:/app/faiss_index
      - ai_logs:/app/logs
    depends_on:
      - postgres
      - minio
    networks:
      - ai-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ai_ops
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - ai-network
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/documents;
      /usr/bin/mc policy set public myminio/documents;
      exit 0;
      "
    networks:
      - ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  redis_data:
  ai_data:
  ai_faiss:
  ai_logs:

networks:
  ai-network:
    driver: bridge